spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall #开启监控和防火墙功能
      aop-patterns: com.diodi.admin.* #监控spring这个包下的所有组件
      stat-view-servlet:
        enabled: true #开启德鲁伊的监控页功能
        login-username: admin
        login-password: admin
        reset-enable: false #重置按钮禁用
      web-stat-filter:
        enabled: true #监控web应用的
        url-pattern: /* #匹配哪些
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'  #排除哪些
      filter:
        stat: #监控
          slow-sql-millis: 1000 #慢查询
          log-slow-sql: true #是否记录慢查询
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false #不允许删表
  #    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 3
  boot:
    admin:
      client:
        url: http://localhost:8081
        instance:
          prefer-ip: true #使用IP注册实例
  application:
    name: boot-05-web-admin
#  redis:
#    host: r-bp12bxvum7rvlfgemupd.redis.rds.aliyuncs.com
#    port: 6379
#    password: diodi:IhvJvuL5HoEQ
#    client-type: jedis
#    jedis:
#      pool:
#        max-active: 10
#    lettuce:
#      pool:
#        max-idle: 10
#        min-idle: 5

#    url: redis://diodi:IhvJvuL5HoEQ@r-bp12bxvum7rvlfgemupd.redis.rds.aliyuncs.com:6379

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#指标监控
#management 是所有actuator的配置
#management.endpoint.端点名.XXXX 对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true #默认开启所有监控端点
    web:
      exposure:
        include: '*' #以web模式暴露所有端点
  endpoint:
    health:
      show-details: always #健康检查显示详细信息
