spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true #开启请求参数内容协商模式
  resources:
    add-mappings: true
    cache:
      period: 11000
server:
  servlet:
    context-path: /world